First steps of My portfolio project: toolbar and headline
CindyDorantes/My-personal-portfolio-site pull request #1
Opened 2022-06-02 23:11 UTC by CindyDorantes

- Add index.html file with 2 sections: toolbar and headline
- Add style.css file for styling according to template 3 (available in Figma)
- Add README file
- Install and run linters

2022-06-02 23:20 UTC, ShahierNashaat requested changes
Hi @CindyDorantes , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-02 23:20 UTC, ShahierNashaat commented on Index.html
> +        <span class="welcome">Welcome</span>
- [ ] Kindly be noticed that the logo should be inside a link (`a` tag).

2022-06-02 23:20 UTC, ShahierNashaat commented on Index.html
> +        <span class="hamburguer"><img src="./Images/Union.png" alt="hamburguer menu"></span>
- [ ] Kindly be noticed that the hamburger button should be inside a `nav` tag.

2022-06-02 23:20 UTC, ShahierNashaat commented on Index.html
> +        </h1>
- [ ] Kindly make the title in an `h1` tag and the subtitle in an `hx` tag (examples: `<h1>,<h2>,<h3>,` etc...).
- [ ] so for example:-
```
<h1>Hey there. I'm Cindy</h1>
<h2>I'm a software developer</h2>
```

2022-06-02 23:20 UTC, ShahierNashaat commented on Index.html
> +        </h2>
- [ ] Kindly be noticed that you should put this paragraph in a `p` tag.

2022-06-02 23:20 UTC, ShahierNashaat commented on Index.html
> +        </nav>
- [ ] Kindly remove the `nav` tag from this section as it shouldn't be here.

2022-06-03 00:02 UTC, rukundoeric approved these changes
Hi @CindyDorantes,

_Excellent job on this project. Keep it up 🎆_

_Congratulations! 🎉  on the splendid job 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_

## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 


Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

------
>As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-06-03 00:30 UTC, merged