Implement Popup window
CindyDorantes/My-personal-portfolio-site pull request #7
Opened 2022-06-22 22:53 UTC by CindyDorantes

First review request. Interactions implemented:
- When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
- When the user clicks (or taps) the close (X) button, the popup disappears
- Popups for both mobile and desktop screen sizes
- Use a JavaScript array to store all of the information for all projects.

Second review request. Changes introduced:
- Fix scroll
- Fix desktop design

2022-06-22 23:01 UTC, Ismailco reviewed
Hi Team,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has linters errors, kindly fix this so the linter checks are green and passing

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-06-24 00:15 UTC, keroloussamy requested changes
Hi @CindyDorantes, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️

## Required Changes ♻️
_Check the comments under the review._

![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-24 00:15 UTC, keroloussamy commented on style.css
> +}
- [ ] Kindly I can't see the close button, kindly add it to match the Figma design.
- [ ] Kindly I can't see the tags and the paragraph, kindly add them to match the Figma design.
- [ ] Kindly make the pic take the whole width, to match the Figma design.

Your design
![image](https://user-images.githubusercontent.com/35535130/175435275-016dba6d-fcda-4ee3-86ef-4fa97696cc82.png)

Figma design
![image](https://user-images.githubusercontent.com/35535130/175435362-1cba460f-b63b-4e5a-86e4-2f14840938d1.png)

2022-06-24 00:15 UTC, keroloussamy commented on style.css
> +
- [ ] Kindly for the mobile version, I can't see the whole paragraph and the two buttons. Kindly make them visible or add scroll.

Your design
![image](https://user-images.githubusercontent.com/35535130/175435608-aae05e62-5e28-4758-997b-a5e1e870a1ea.png)

Original design
![image](https://user-images.githubusercontent.com/35535130/175435663-31b31b64-4252-4918-bda7-89ba0f4a1599.png)

2022-06-24 17:31 UTC, youmari approved these changes
# Project Approved :trophy: :tada: 🟢 

Hi @CindyDorantes 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linters error.
:heavy_check_mark: Details PR title and description.
:heavy_check_mark: Good commit messages.

Cheers and Happy coding!👏👏👏
 

- [ ] [optional] for tablet screen your overlay doesn't cover the whole screen so it would be better if you fix it
![image](https://user-images.githubusercontent.com/61790587/175612604-92f78c25-1b72-4de3-9339-78656e3a376f.png)


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U02FTTCCU2V)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-06-24 18:31 UTC, merged